name: MineTweet_for_Plugin
main: com.ittekikun.plugin.minetweet.MineTweet
version: 1.48
description: Twitter on your Server.
authors: [ittekikun]
website: http://forum.minecraftuser.jp/viewtopic.php?f=38&t=12469
softdepend: [LunaChat, MCBans, Votifier]

commands:
   MineTweet:
      description: This is a minetweet command.
      usage: "Usage: /minetweet [args]"
   Mt:
      description: This is a minetweet command.
      usage: "Usage: /mt [args]"
      
permissions:
  MineTweet.*:
    description: Permission to perform all commands.
    default: op
  MineTweet.Reload:
    description: Permission to Reload configuration..
    default: op
  MineTweet.Tweet:
    description: Permission to Tweet command.
    default: op